name: avr8_dart
description: A Dart library that implements the AVR 8-bit architecture, enabling simulation of Arduino and ATmega microcontrollers.
version: 0.1.0
repository: https://github.com/burhankhanzada/avr8_dart
environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
